export type StickerTone = 'couples' | 'romantic' | 'flirty' | 'darkHumour';
export type StickerAnimation = 'pulse' | 'float' | 'spin' | 'burst' | 'shake' | 'bounce';

export type Sticker = {
  id: string;
  tone: StickerTone;
  emoji: string;
  label: string;
  message: string;
  animation: StickerAnimation;
  accent: string;
};

const animations: StickerAnimation[] = ['pulse', 'float', 'spin', 'burst', 'shake', 'bounce'];

const accents = {
  couples: ['#FF5C97', '#FFB3C7', '#FF6FAE', '#F78BD8', '#FF6B6B', '#F9A8D4'],
  romantic: ['#FF4F6D', '#FF8FB3', '#FFDE59', '#86B6FF', '#DDEBFF', '#FFD54A'],
  flirty: ['#FF7A90', '#FF4B32', '#B8325E', '#FB7185', '#F472B6', '#F97316'],
  darkHumour: ['#EF4444', '#A855F7', '#818CF8', '#60A5FA', '#F97316', '#64748B'],
};

const stickerSeeds: Array<Omit<Sticker, 'animation' | 'accent'>> = [
  { id: 'couple-heart-bloom', tone: 'couples', emoji: '💞', label: 'Heart bloom', message: 'Heart bloom' },
  { id: 'couple-hug', tone: 'couples', emoji: '🤗', label: 'Warm hug', message: 'Warm hug' },
  { id: 'couple-miss-you', tone: 'couples', emoji: '🥺', label: 'Miss you', message: 'Miss you' },
  { id: 'couple-good-night', tone: 'couples', emoji: '🌙', label: 'Good night', message: 'Good night' },
  { id: 'couple-forever', tone: 'couples', emoji: '♾️', label: 'Forever', message: 'Forever' },
  { id: 'couple-two-hearts', tone: 'couples', emoji: '💕', label: 'Two hearts', message: 'Two hearts' },
  { id: 'couple-cuddle', tone: 'couples', emoji: '🧸', label: 'Cuddle', message: 'Cuddle time' },
  { id: 'couple-magnetic', tone: 'couples', emoji: '🧲', label: 'Magnetic', message: 'You pull me in' },
  { id: 'couple-lock-heart', tone: 'couples', emoji: '🔐', label: 'Locked in', message: 'Locked in' },
  { id: 'couple-soft-drama', tone: 'couples', emoji: '🎭', label: 'Love drama', message: 'Our little drama' },
  { id: 'couple-soulmate', tone: 'couples', emoji: '🫶', label: 'Soulmate', message: 'Soulmate energy' },
  { id: 'couple-jealous', tone: 'couples', emoji: '👀', label: 'Only mine', message: 'Only mine' },
  { id: 'couple-pinky', tone: 'couples', emoji: '🤙', label: 'Pinky vibe', message: 'Pinky promise vibe' },
  { id: 'couple-home', tone: 'couples', emoji: '🏡', label: 'Home', message: 'You feel like home' },
  { id: 'couple-playlist', tone: 'couples', emoji: '🎧', label: 'Our song', message: 'Our song' },
  { id: 'couple-pillow', tone: 'couples', emoji: '🛏️', label: 'Cozy', message: 'Cozy time' },
  { id: 'couple-snack', tone: 'couples', emoji: '🍫', label: 'Sweet', message: 'Sweet treat' },
  { id: 'couple-rain', tone: 'couples', emoji: '🌧️', label: 'Rain date', message: 'Rain date' },
  { id: 'couple-hands', tone: 'couples', emoji: '🤝', label: 'Together', message: 'Together' },
  { id: 'couple-camera', tone: 'couples', emoji: '📸', label: 'Memory', message: 'Memory made' },
  { id: 'couple-ticket', tone: 'couples', emoji: '🎟️', label: 'Movie date', message: 'Movie date' },
  { id: 'couple-map', tone: 'couples', emoji: '🗺️', label: 'Adventure', message: 'Adventure with you' },
  { id: 'couple-anchor', tone: 'couples', emoji: '⚓', label: 'Anchor', message: 'You anchor me' },
  { id: 'couple-bubble-tea', tone: 'couples', emoji: '🧋', label: 'Boba date', message: 'Boba date' },
  { id: 'couple-sleepy', tone: 'couples', emoji: '😴', label: 'Sleepy call', message: 'Sleepy call' },
  { id: 'couple-soft-heart', tone: 'couples', emoji: '💗', label: 'Soft heart', message: 'Soft heart' },
  { id: 'couple-honey', tone: 'couples', emoji: '🍯', label: 'Honey', message: 'Honey mood' },
  { id: 'couple-umbrella', tone: 'couples', emoji: '☂️', label: 'Cover me', message: 'Cover me' },
  { id: 'couple-plant', tone: 'couples', emoji: '🪴', label: 'Growing', message: 'Growing together' },
  { id: 'couple-lucky', tone: 'couples', emoji: '🍀', label: 'Lucky us', message: 'Lucky us' },
  { id: 'couple-gift', tone: 'couples', emoji: '🎁', label: 'Surprise', message: 'Surprise' },
  { id: 'couple-teddy-heart', tone: 'couples', emoji: '🧸', label: 'Teddy hug', message: 'Teddy hug' },
  { id: 'couple-warm-soup', tone: 'couples', emoji: '🍜', label: 'Care', message: 'Take care' },
  { id: 'couple-dream', tone: 'couples', emoji: '💭', label: 'Thinking', message: 'Thinking of you' },
  { id: 'couple-pin', tone: 'couples', emoji: '📍', label: 'My place', message: 'My favourite place' },
  { id: 'couple-bells', tone: 'couples', emoji: '🔔', label: 'Reminder', message: 'Reminder: us' },
  { id: 'couple-spark', tone: 'couples', emoji: '✨', label: 'Spark', message: 'Still sparkling' },
  { id: 'couple-peace', tone: 'couples', emoji: '🕊️', label: 'Peace', message: 'My peace' },
  { id: 'couple-warmth', tone: 'couples', emoji: '🧣', label: 'Warmth', message: 'Warmth' },
  { id: 'couple-us', tone: 'couples', emoji: '👩‍❤️‍👨', label: 'Us', message: 'Us' },

  { id: 'romantic-roses', tone: 'romantic', emoji: '🌹', label: 'Roses', message: 'Roses for you' },
  { id: 'romantic-love-letter', tone: 'romantic', emoji: '💌', label: 'Love note', message: 'Love note' },
  { id: 'romantic-sparkle-love', tone: 'romantic', emoji: '💖', label: 'Sparkle love', message: 'Sparkle love' },
  { id: 'romantic-butterflies', tone: 'romantic', emoji: '🦋', label: 'Butterflies', message: 'Butterflies' },
  { id: 'romantic-promise', tone: 'romantic', emoji: '💍', label: 'Promise', message: 'Promise' },
  { id: 'romantic-sunflower', tone: 'romantic', emoji: '🌻', label: 'Sunshine', message: 'My sunshine' },
  { id: 'romantic-cloud-nine', tone: 'romantic', emoji: '☁️', label: 'Cloud nine', message: 'Cloud nine' },
  { id: 'romantic-moon-back', tone: 'romantic', emoji: '🚀', label: 'Moon back', message: 'To the moon and back' },
  { id: 'romantic-candle', tone: 'romantic', emoji: '🕯️', label: 'Candlelight', message: 'Candlelight mood' },
  { id: 'romantic-diamond', tone: 'romantic', emoji: '💎', label: 'Precious', message: 'Precious' },
  { id: 'romantic-stars', tone: 'romantic', emoji: '🌌', label: 'Stars', message: 'Under the stars' },
  { id: 'romantic-music', tone: 'romantic', emoji: '🎶', label: 'Serenade', message: 'Serenade' },
  { id: 'romantic-poetry', tone: 'romantic', emoji: '📜', label: 'Poetry', message: 'Poetry mood' },
  { id: 'romantic-champagne', tone: 'romantic', emoji: '🥂', label: 'Cheers us', message: 'Cheers to us' },
  { id: 'romantic-swan', tone: 'romantic', emoji: '🦢', label: 'Grace', message: 'Graceful love' },
  { id: 'romantic-lotus', tone: 'romantic', emoji: '🪷', label: 'Bloom', message: 'Love blooms' },
  { id: 'romantic-comet', tone: 'romantic', emoji: '☄️', label: 'Cosmic', message: 'Cosmic love' },
  { id: 'romantic-envelope-heart', tone: 'romantic', emoji: '💟', label: 'My heart', message: 'My heart' },
  { id: 'romantic-garden', tone: 'romantic', emoji: '🌷', label: 'Garden', message: 'Love garden' },
  { id: 'romantic-sunset', tone: 'romantic', emoji: '🌅', label: 'Sunset', message: 'Sunset with you' },
  { id: 'romantic-melody', tone: 'romantic', emoji: '🎻', label: 'Melody', message: 'Melody for you' },
  { id: 'romantic-wish', tone: 'romantic', emoji: '🌠', label: 'Wish', message: 'Wish came true' },
  { id: 'romantic-crown', tone: 'romantic', emoji: '👑', label: 'Royal', message: 'My royal one' },
  { id: 'romantic-soft-kiss', tone: 'romantic', emoji: '💋', label: 'Soft kiss', message: 'Soft kiss' },
  { id: 'romantic-heart-ribbon', tone: 'romantic', emoji: '💝', label: 'Ribbon heart', message: 'Wrapped heart' },
  { id: 'romantic-dove-note', tone: 'romantic', emoji: '🕊️', label: 'Love peace', message: 'Love peace' },
  { id: 'romantic-violet', tone: 'romantic', emoji: '💜', label: 'Violet love', message: 'Violet love' },
  { id: 'romantic-blossom', tone: 'romantic', emoji: '🌸', label: 'Blossom', message: 'Blossom' },
  { id: 'romantic-cupid', tone: 'romantic', emoji: '🏹', label: 'Cupid', message: 'Cupid got me' },
  { id: 'romantic-planet', tone: 'romantic', emoji: '🪐', label: 'Orbit', message: 'In your orbit' },
  { id: 'romantic-silk', tone: 'romantic', emoji: '🎀', label: 'Ribbon', message: 'Soft ribbon' },
  { id: 'romantic-palette', tone: 'romantic', emoji: '🎨', label: 'Colors', message: 'You color my day' },
  { id: 'romantic-lamp', tone: 'romantic', emoji: '🏮', label: 'Glow', message: 'You glow' },
  { id: 'romantic-wave', tone: 'romantic', emoji: '🌊', label: 'Tide', message: 'Love tide' },
  { id: 'romantic-key', tone: 'romantic', emoji: '🗝️', label: 'Key', message: 'Key to me' },
  { id: 'romantic-book', tone: 'romantic', emoji: '📖', label: 'Story', message: 'Our story' },
  { id: 'romantic-mailbox', tone: 'romantic', emoji: '📮', label: 'Sent love', message: 'Sent love' },
  { id: 'romantic-fireflies', tone: 'romantic', emoji: '💫', label: 'Fireflies', message: 'Firefly love' },
  { id: 'romantic-necklace', tone: 'romantic', emoji: '📿', label: 'Charm', message: 'My charm' },
  { id: 'romantic-heart-arrow', tone: 'romantic', emoji: '💘', label: 'Arrow', message: 'Heart arrow' },

  { id: 'flirty-kiss', tone: 'flirty', emoji: '😘', label: 'Kiss', message: 'Kiss' },
  { id: 'flirty-hot-heart', tone: 'flirty', emoji: '❤️‍🔥', label: 'Hot heart', message: 'Hot heart' },
  { id: 'flirty-date-night', tone: 'flirty', emoji: '🍷', label: 'Date night', message: 'Date night' },
  { id: 'flirty-sweetheart', tone: 'flirty', emoji: '🍓', label: 'Sweetheart', message: 'Sweetheart' },
  { id: 'flirty-shy-smile', tone: 'flirty', emoji: '☺️', label: 'Shy smile', message: 'Shy smile' },
  { id: 'flirty-wink', tone: 'flirty', emoji: '😉', label: 'Wink', message: 'Wink wink' },
  { id: 'flirty-lipstick', tone: 'flirty', emoji: '💄', label: 'Lipstick', message: 'Getting cute for you' },
  { id: 'flirty-spark-eyes', tone: 'flirty', emoji: '😍', label: 'Eyes on you', message: 'Eyes on you' },
  { id: 'flirty-blush', tone: 'flirty', emoji: '🤭', label: 'Blushing', message: 'Blushing' },
  { id: 'flirty-firework', tone: 'flirty', emoji: '🎆', label: 'Chemistry', message: 'Chemistry' },
  { id: 'flirty-peachy', tone: 'flirty', emoji: '🍑', label: 'Peachy', message: 'Peachy mood' },
  { id: 'flirty-cherry', tone: 'flirty', emoji: '🍒', label: 'Cherry', message: 'Cherry cute' },
  { id: 'flirty-spark-lips', tone: 'flirty', emoji: '💋', label: 'Lips', message: 'Lips sealed' },
  { id: 'flirty-sizzle', tone: 'flirty', emoji: '🔥', label: 'Sizzle', message: 'Sizzle' },
  { id: 'flirty-perfume', tone: 'flirty', emoji: '🧴', label: 'Perfume', message: 'Perfume mood' },
  { id: 'flirty-satin', tone: 'flirty', emoji: '🪞', label: 'Mirror', message: 'Mirror check' },
  { id: 'flirty-dance', tone: 'flirty', emoji: '💃', label: 'Dance', message: 'Dance with me' },
  { id: 'flirty-suit', tone: 'flirty', emoji: '🕺', label: 'Smooth', message: 'Smooth moves' },
  { id: 'flirty-martini', tone: 'flirty', emoji: '🍸', label: 'Martini', message: 'Martini mood' },
  { id: 'flirty-honey', tone: 'flirty', emoji: '🍯', label: 'Honey', message: 'Honey' },
  { id: 'flirty-sugar', tone: 'flirty', emoji: '🍭', label: 'Sugar', message: 'Sugar rush' },
  { id: 'flirty-dimples', tone: 'flirty', emoji: '😏', label: 'Smirk', message: 'Smirk' },
  { id: 'flirty-mystery', tone: 'flirty', emoji: '🌫️', label: 'Mystery', message: 'Mystery mood' },
  { id: 'flirty-sparkle', tone: 'flirty', emoji: '🌟', label: 'Shine', message: 'You shine' },
  { id: 'flirty-candy', tone: 'flirty', emoji: '🍬', label: 'Candy', message: 'Candy crush' },
  { id: 'flirty-heatwave', tone: 'flirty', emoji: '🌶️', label: 'Spicy', message: 'Spicy mood' },
  { id: 'flirty-glow', tone: 'flirty', emoji: '💅', label: 'Glow up', message: 'Glow up' },
  { id: 'flirty-radar', tone: 'flirty', emoji: '📡', label: 'Signal', message: 'Flirty signal' },
  { id: 'flirty-magic', tone: 'flirty', emoji: '🪄', label: 'Magic', message: 'Magic touch' },
  { id: 'flirty-late-night', tone: 'flirty', emoji: '🌃', label: 'Late night', message: 'Late night mood' },
  { id: 'flirty-neon', tone: 'flirty', emoji: '🪩', label: 'Neon', message: 'Neon mood' },
  { id: 'flirty-silk-heart', tone: 'flirty', emoji: '🩷', label: 'Pink heart', message: 'Pink heart' },
  { id: 'flirty-warm', tone: 'flirty', emoji: '🥵', label: 'Warm', message: 'Warm mood' },
  { id: 'flirty-cute-trouble', tone: 'flirty', emoji: '😈', label: 'Trouble', message: 'Cute trouble' },
  { id: 'flirty-slow-burn', tone: 'flirty', emoji: '🕯️', label: 'Slow burn', message: 'Slow burn' },
  { id: 'flirty-secret', tone: 'flirty', emoji: '🤫', label: 'Secret', message: 'Secret smile' },

  { id: 'dark-red-flag', tone: 'darkHumour', emoji: '🚩', label: 'Red flag', message: 'That is a red flag' },
  { id: 'dark-toxic-love', tone: 'darkHumour', emoji: '🧪', label: 'Toxic cute', message: 'Toxic but cute' },
  { id: 'dark-overthinking', tone: 'darkHumour', emoji: '🧠', label: 'Overthink', message: 'Overthinking unlocked' },
  { id: 'dark-cry-laugh', tone: 'darkHumour', emoji: '😭', label: 'Crying LOL', message: 'Laughing through pain' },
  { id: 'dark-chaos', tone: 'darkHumour', emoji: '🫠', label: 'Meltdown', message: 'Tiny meltdown' },
  { id: 'dark-broke-heart', tone: 'darkHumour', emoji: '💔', label: 'RIP heart', message: 'RIP my heart' },
  { id: 'dark-suspicious', tone: 'darkHumour', emoji: '🕵️', label: 'Sus', message: 'Suspicious behaviour' },
  { id: 'dark-no-sleep', tone: 'darkHumour', emoji: '☕', label: 'No sleep', message: 'No sleep, only vibes' },
  { id: 'dark-burnout', tone: 'darkHumour', emoji: '🔋', label: 'Burnout', message: 'Emotionally buffering' },
  { id: 'dark-seen-zone', tone: 'darkHumour', emoji: '📵', label: 'Seen zone', message: 'Welcome to seen zone' },
  { id: 'dark-delulu', tone: 'darkHumour', emoji: '🤡', label: 'Delulu', message: 'Delulu is the plan' },
  { id: 'dark-main-character', tone: 'darkHumour', emoji: '🎬', label: 'Main drama', message: 'Main character crisis' },
  { id: 'dark-loading-love', tone: 'darkHumour', emoji: '⏳', label: 'Loading', message: 'Feelings loading' },
  { id: 'dark-silent-treatment', tone: 'darkHumour', emoji: '🤐', label: 'Silent', message: 'Silent treatment loading' },
  { id: 'dark-receipts', tone: 'darkHumour', emoji: '🧾', label: 'Receipts', message: 'I have receipts' },
  { id: 'dark-typing-war', tone: 'darkHumour', emoji: '⌨️', label: 'Typing war', message: 'Typing war' },
  { id: 'dark-low-battery', tone: 'darkHumour', emoji: '🪫', label: 'Low battery', message: 'Social battery low' },
  { id: 'dark-awkward', tone: 'darkHumour', emoji: '🙃', label: 'Awkward', message: 'Awkward but okay' },
  { id: 'dark-drama-tea', tone: 'darkHumour', emoji: '🍵', label: 'Tea', message: 'Drama tea' },
  { id: 'dark-cancel-plans', tone: 'darkHumour', emoji: '🛋️', label: 'Plans no', message: 'Cancelling plans emotionally' },
  { id: 'dark-buffering', tone: 'darkHumour', emoji: '🔄', label: 'Buffering', message: 'Brain buffering' },
  { id: 'dark-mood-swing', tone: 'darkHumour', emoji: '🎢', label: 'Mood ride', message: 'Mood rollercoaster' },
  { id: 'dark-not-today', tone: 'darkHumour', emoji: '🙅', label: 'Not today', message: 'Not today' },
  { id: 'dark-soft-block', tone: 'darkHumour', emoji: '🚧', label: 'Soft block', message: 'Soft block energy' },
  { id: 'dark-eye-roll', tone: 'darkHumour', emoji: '🙄', label: 'Eye roll', message: 'Respectfully no' },
  { id: 'dark-snack-cope', tone: 'darkHumour', emoji: '🍿', label: 'Coping', message: 'Coping with snacks' },
  { id: 'dark-brain-tab', tone: 'darkHumour', emoji: '🗂️', label: 'Tabs', message: 'Too many tabs open' },
  { id: 'dark-fake-calm', tone: 'darkHumour', emoji: '🧘', label: 'Fake calm', message: 'Fake calm activated' },
  { id: 'dark-plot-twist', tone: 'darkHumour', emoji: '📉', label: 'Plot twist', message: 'Plot twist again' },
  { id: 'dark-unhinged', tone: 'darkHumour', emoji: '🌀', label: 'Unhinged', message: 'Slightly unhinged' },
  { id: 'dark-boundary', tone: 'darkHumour', emoji: '🧱', label: 'Wall', message: 'Emotional wall' },
  { id: 'dark-side-eye', tone: 'darkHumour', emoji: '🫥', label: 'Side eye', message: 'Side eye' },
  { id: 'dark-last-nerve', tone: 'darkHumour', emoji: '🪢', label: 'Last nerve', message: 'Last nerve' },
  { id: 'dark-panic-smile', tone: 'darkHumour', emoji: '😬', label: 'Panic smile', message: 'Panic smile' },
  { id: 'dark-message-draft', tone: 'darkHumour', emoji: '📝', label: 'Drafting', message: 'Drafting a comeback' },
  { id: 'dark-mental-vacation', tone: 'darkHumour', emoji: '🏝️', label: 'Checked out', message: 'Mentally on vacation' },
];

export const stickers: Sticker[] = stickerSeeds.map((sticker, index) => ({
  ...sticker,
  animation: animations[index % animations.length],
  accent: accents[sticker.tone][index % accents[sticker.tone].length],
}));

export const getStickerById = (id?: string | null) => stickers.find((sticker) => sticker.id === id);
